### ISSUE TITLE
Colour themes dont always work

### ISSUE THREAD

**Issue by dangerdak** [FAC-11/AllAboutMe#167]
Tick marks and colour changing don't work for Nick, even on chrome on desktop (strange as they work for us...). Dont work for me in incognito mode. Maybe because it uses cookies

![themes-no-ticks](https://user-images.githubusercontent.com/2583099/32662472-91a5178a-c622-11e7-8636-00136ace2dea.jpg)

**Comment by polyccon** [comment]
Perhaps we could use local storage instead of cookies and this will be an easier fix than we thought.

**Comment by dangerdak** [comment]
@polyccon I think this was addressed in pr #173 - shall we try pushing it to heroku and ask nick to try it out again?

**Comment by polyccon** [comment]
@dangerdak great let's do it :-)

**Comment by dangerdak** [comment]
nick confirmed that this works now
