### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by sohilpandya** [FAC-11/AllAboutMe#174]
Hey, I am just going through the setup in the readme and noting some of the points down below. 

- [ ] What should the db_name be in our case? Should we keep it consistent or give the user the choice of naming it anything they want?  
- [x] Does this work for you `CREATE USER [user_name] WITH PASSWORD [password];` I get a syntax error when entering the password. 
- [x] link to running the db_build is incorrect. missing the `model` directory
- [x] Where are we storing the env variables at the moment? ( google docs?) We should store it in a google docs if we aren't already so that we can share that with the new members of the team, making the setup process easier. 
- [x] `TEMPLATE_DIRECTORY` should be set in the example env, as we need it before running the app.

**Comment by dangerdak** [comment]
I think the db_name doesn't matter at all, right? It just affects what the DB_URL will be in the local config.env

**Comment by dangerdak** [comment]
And I've made a google docs, I can share it with you if you give me your email @sohilpandya
