### ISSUE TITLE
Handling of Routes 

### ISSUE THREAD

**Issue by sohilpandya** [FAC-11/AllAboutMe#175]
I am slightly confused by the flow that we have for routes in the app. I'll take the example of `home`.

- In `app.js` we use `/home` route and run the `requireLogin` function which will either grant/deny access to the given page. 
- If the user is denied access, we are rendering the login page, but we are not redirecting the user, so the user still sees the same endpoint as before, is flow clear or should we think about redirecting the user to `/` so they know they have been denied access and are redirected to homepage or login page. 
- If the user is granted access, then I have to look into controller index and find the appropriate file, in this case, the `home.js` file. Can we not combine the two either in the `app.js` or `controller/index.js` so that we have all the information for a given route in one place? 
    - For e.g. we can do the following to the home route `router.get(`/home`, requireLogin, home.get)`

What are your thoughts on these two points?

**Comment by dangerdak** [comment]
I agree with them both - didn't know you could do the second point that way, thanks. I would be more inclined to combine the two in controller/index.js as we expect to see all our endpoints in this file - what do you think @polyccon ?

**Comment by polyccon** [comment]
I also agree with both points and also agree with choosing ```controllers/index.js``` :+1:

**Comment by polyccon** [comment]
So the first point is actually covered in this PR: #192
The second point I'm not sure it's actually possible and/or necessary. Any thought or ideas on how and why might we implement this?
@sohilpandya
