### ISSUE TITLE
Content of the controller directory

### ISSUE THREAD

**Issue by sohilpandya** [FAC-11/AllAboutMe#177]
The controller directory should contain information related to the controllers that are being handled by endpoints, in our case I've found a few files that don't deal with that scenario. 
- `passwordModule`
- `helper` 
- `validate`
- `check_email`

Where do you think these files belong?

**Comment by polyccon** [comment]
Thanks for raising an issue we were already planning some restructuring of the "controllers" directory and move the above files into a "helpers" one.

**Comment by sohilpandya** [comment]
Keep require login file inside the controller. 👍
