### ISSUE TITLE
Mixing camelCase and snake_case

### ISSUE THREAD

**Issue by sohilpandya** [FAC-11/AllAboutMe#178]
I've noticed that we are not using both camelCase and snake_case for defining our files. We should be consistent and try to use one of the formats. 

As an example our controller directory contains a few snake_case file names and some camelCase file names. 
- `check_email`
- `checkTheme`

Thoughts?

**Comment by polyccon** [comment]
I would choose snake case for file names, to avoid problems with case sensitivity issues when switching operating systems, and keep camel case for function names if you agree.
What do you think @dangerdak ?

**Comment by sohilpandya** [comment]
As long as you have a system in place 😊 I am happy with it so long as it's consistent.
