### ISSUE TITLE
Setting up code coverage

### ISSUE THREAD

**Issue by sohilpandya** [FAC-11/AllAboutMe#180]
Have we thought about trying to implement code coverage for this project?

**Comment by dangerdak** [comment]
We have code coverage set up ![cov](https://user-images.githubusercontent.com/2583099/32726500-20694f2c-c871-11e7-8a0f-8d4e6370cb75.jpg)

also `npm run coverage` should work

**Comment by sohilpandya** [comment]
Thanks for that :)
