### ISSUE TITLE
color scheme designer tool

### ISSUE THREAD

**Issue by nickpovey** [FAC-11/AllAboutMe#19]
This is awesome, I've used this for web design in the past. Check it out, it might be useful.

http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF

**Comment by Jen-Harris** [comment]
thanks! 

We love [Coolors](https://coolors.co/) for generating random colour combinations 

When you have suggestions it's best to but a comment in an existing issue (in this case issue #2) so we can refer to it when we start to work on it 👍
