### ISSUE TITLE
Colour theme choice

### ISSUE THREAD

**Issue by rebecacalvoquintero** [FAC-11/AllAboutMe#2]
- [x] As a user I can choose my colour theme
- [x] The theme will affect the whole app
- [x] The theme should take effect without having to refresh the page
- [x] The theme should be the same on my next visit
  - [x] Even without the user having to log in - cookies?
- [x] Checkbox should be ticked for current theme

**Comment by dangerdak** [comment]
Could pass class names into handlebars?
