### ISSUE TITLE
css

### ISSUE THREAD

**Issue by rebecacalvoquintero** [FAC-11/AllAboutMe#28]
- [x] use tachyons
- [x] Login 
- [x] signup 
- [x] home 
- [x] progress
- [x] choose colour
- [x] info page
- [x] appointments
- [x] symptoms
- [x] about me
- [x] background
- [x] send 
- [x] finish
- [x] Modal
- [x] Navbar

**Comment by Jen-Harris** [comment]
styling needed for navbar
![image](https://user-images.githubusercontent.com/26116988/31441471-26cec694-ae8b-11e7-8f8d-321ba3901a11.png)
