### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by polyccon** [FAC-11/AllAboutMe#33]
Functionality for the users to reset their passwords should they forget them would be nice to add.
- [x] /forgot GET: User enters email address
- [x] /forgot POST:
  - [x] Check entered email address is registered
  - [x] Generate unique reset token
  - [x] Store token and users email in redis
  - [x] Email link containing token to user
  - [x] Token should expire ([see comment](https://github.com/FAC-11/AllAboutMe/issues/33#issuecomment-341154085))
  - [x] Token should be single-use (use [del](https://redis.io/commands/del) command after we've finished with it. All redis commands are available in [node-redis module](https://github.com/NodeRedis/node_redis#sending-commands))
- [x] /reset/:token GET: 
  - [x] Check token in url is valid by accessing it in redis
  - [x] User enters new password (twice)
- [x] /reset POST:
  - [x] Get email associated with token being used
  - [x] New password should be validated just like original one is (e.g. more than 8 characters)
  - [x] Use email to update users password in db
  - [x] Redirect to /login and provide success flash message

**Comment by dangerdak** [comment]
Add expiry to key: https://github.com/NodeRedis/node_redis#redis-commands
```js
// this key will expire after 10 seconds
client.set('key', 'value!', 'EX', 10);
```
