### ISSUE TITLE
What precautions do we need to take for data protection? 

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/AllAboutMe#47]
Hey @nickpovey, we were chatting yesterday and starting thinking about data security as @sofer mentioned this is particularly stringent within the NHS. 
Are you or Alex able to let us know what measures we need to put in place?

**Comment by nickpovey** [comment]
i'll be perfectly honest I am not sure, and unfortunately alex is on leave
till next monday. nikki from the participation group might be able to help,
but id be cautious of asking her, it will probably look a bit bad and not
re assure her of the security of it. not sure what to do in this situation

**Comment by Jen-Harris** [comment]
Hey @nickpovey,
Don't worry about the security of the app, this is all total in hand!
Data protection is just a slightly different aspect which is typically not a problem with general apps. However, we believe there are additional layers required for NHS products. 
If you are able to chat to Niki that would be great? And if she has any doubts we would be happy to have a call with her

**Comment by nickpovey** [comment]
ok cool. ill copy you in on an email

**Comment by dangerdak** [comment]
see #100
