### ISSUE TITLE
App status 

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/AllAboutMe#48]
Hey @nickpovey,
We're looking good to get a working product ready for Friday 👍 . Unfortunately we have had a bit less time that we expected when we were scoping the product so realistically I don't think we'll be able to get all the extra features finished. 
We are unlikely to get the drawing or speech element finished or the offline aspect. But we are still aiming to incorporate the colour choice 😄 I hope this is OK! 
If we have a second sprint these will be top priority!

**Comment by nickpovey** [comment]
thanks for all your hard work so far
