### ISSUE TITLE
Send the form

### ISSUE THREAD

**Issue by rebecacalvoquintero** [FAC-11/AllAboutMe#6]
- [x] Being able to send the form to an external person: the clinician
- [ ] the data will be exported as a pdf/ word document

**Comment by Jen-Harris** [comment]
@rebecacalvoquintero what's the point of the form?

**Comment by rebecacalvoquintero** [comment]
@njsfield Nick, sorry to bother you, I am pretty sure you have loads to do.We know about your huge project with AF. We are doing a similar thing in this project and I have come accross with nodemailer. But I do not seem to find very useful examples. Have you used it before?

**Comment by polyccon** [comment]
will create a separate issue for saving the form as pdf

**Comment by dangerdak** [comment]
pdf for next sprint :)
